### ISSUE TITLE
Application doesn't run at all

### ISSUE THREAD

**Issue by tanja84dk** [TheCherno/Walnut-Chat#4]
I have tried to run the version 1.2 several times, but unfortunally at first it said it were missing a vulkan dll.
I then made sure vulkan Runtime were installed by installing the newest version og Vulkan Runrime again from https://vulkan.lunarg.com/sdk/home and sure it stopped erroring about a missing vulkan dll but unfortunally then its just closing right after tried to load

**Comment by breaddev-here** [comment]
idk what do

**Comment by penguin359** [comment]
Can you try adding the directory with the Vulkan DLL to your PATH environment variable? Have you tried copying the DLL into the same folder as the EXE you are trying to run?

**Comment by tanja84dk** [comment]
> Can you try adding the directory with the Vulkan DLL to your PATH environment variable? Have you tried copying the DLL into the same folder as the EXE you are trying to run?

Well tbh I made the issue over a half year ago and since there were no responses back then I literally deleted it from my pc, but prior i did make sure the vulkan path's etc were is the PATH environment, made sure rebooted etc

And I actually didnt think this issue ticket still were open since it's 7-8 month old
